# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoApplication

  target 'CryptoApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoApplicationUITests' do
    # Pods for testing
  end
  pod 'Alamofire'
  pod ‘SnapKit'

end
